"""Heston lab — the model, its implied-vol surface, and a neural
forward-approximator (the Horvath-Muguruza-Tomas "Deep Learning
Volatility" program, 2019; model: Heston 1993).

Why this exists BEFORE we own options data: the training set is
generated by the model itself. We learn the map
    (kappa, theta, sigma_v, rho, v0)  ->  implied-vol surface (77 pts)
so that when market surfaces arrive, calibration = optimizing 5 inputs
through a microsecond network instead of re-integrating characteristic
functions — the paper's headline is a ~10^4 speedup.

Heston under Q: dS = S sqrt(v) dW1;  dv = kappa(theta - v)dt
+ sigma_v sqrt(v) dW2;  d<W1,W2> = rho dt. Semi-closed pricing via the
characteristic function ("little Heston trap" formulation, Albrecher et
al. 2007), Gauss-Legendre integration; implied vols by vectorized
Newton with bisection fallback.

Gates for the ticket (family: neural-pricing):
  - test-set surface MAE < 0.50 vol points
  - NN surface evaluation >= 100x faster than direct integration
Both must hold or the lab is a tombstone.
"""

from __future__ import annotations

import sys
import time
from datetime import date
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent

RNG = np.random.default_rng(1637)  # the tulip year, obviously
TENORS = np.array([1 / 12, 1 / 6, 1 / 4, 1 / 2, 1.0, 1.5, 2.0])
LOGM = np.linspace(-0.30, 0.30, 11)          # log-moneyness k = ln(K/S)
N_TRAIN, N_TEST = 8000, 1000
GL_N = 96
U, W = np.polynomial.legendre.leggauss(GL_N)
UMAX = 200.0
U = 0.5 * UMAX * (U + 1)                     # nodes on (0, UMAX)
W = 0.5 * UMAX * W


def heston_cf(u: np.ndarray, T: float, kappa, theta, sig, rho, v0):
    """phi(u) = E[exp(iu ln S_T/S_0)], r=0 — little-trap formulation."""
    iu = 1j * u
    d = np.sqrt((rho * sig * iu - kappa) ** 2 + sig ** 2 * (iu + u ** 2))
    g2 = (kappa - rho * sig * iu - d) / (kappa - rho * sig * iu + d)
    e = np.exp(-d * T)
    C = (kappa * theta / sig ** 2) * (
        (kappa - rho * sig * iu - d) * T
        - 2 * np.log((1 - g2 * e) / (1 - g2)))
    D = ((kappa - rho * sig * iu - d) / sig ** 2) * (1 - e) / (1 - g2 * e)
    return np.exp(C + D * v0)


def heston_calls(params, T: float, k: np.ndarray) -> np.ndarray:
    """Call prices (S0=1, r=0) for all strikes K=e^k at one tenor —
    Lewis (2000) single-integral form, vectorized over strikes."""
    kappa, theta, sig, rho, v0 = params
    phi = heston_cf(U - 0.5j, T, kappa, theta, sig, rho, v0)   # (GL_N,)
    integrand = np.real(np.exp(-1j * np.outer(k, U)) * phi
                        / (U ** 2 + 0.25))                     # (nk, GL_N)
    K = np.exp(k)
    return np.maximum(1 - np.sqrt(K) / np.pi * (integrand * W).sum(axis=1),
                      np.maximum(1 - K, 0) + 1e-12)


def bs_call(k, T, vol):
    from scipy.stats import norm
    K = np.exp(k)
    sq = vol * np.sqrt(T)
    d1 = (-k + 0.5 * vol ** 2 * T) / sq
    return norm.cdf(d1) - K * norm.cdf(d1 - sq)


def implied_vol(price, k, T):
    """Vectorized bisection — robust for surface-building."""
    lo = np.full_like(price, 1e-3)
    hi = np.full_like(price, 3.0)
    for _ in range(60):
        mid = 0.5 * (lo + hi)
        too_low = bs_call(k, T, mid) < price
        lo = np.where(too_low, mid, lo)
        hi = np.where(too_low, hi, mid)
    return 0.5 * (lo + hi)


def surface(params) -> np.ndarray:
    return np.concatenate([implied_vol(heston_calls(params, T, LOGM),
                                       LOGM, T) for T in TENORS])


def sample_params(n):
    return np.column_stack([RNG.uniform(0.5, 5.0, n),      # kappa
                            RNG.uniform(0.01, 0.16, n),    # theta
                            RNG.uniform(0.10, 1.00, n),    # sigma_v
                            RNG.uniform(-0.90, 0.0, n),    # rho
                            RNG.uniform(0.01, 0.16, n)])   # v0


def main() -> None:
    from sklearn.neural_network import MLPRegressor
    from sklearn.preprocessing import StandardScaler

    print(f"generating {N_TRAIN + N_TEST} Heston surfaces "
          f"({len(TENORS)}x{len(LOGM)} grid)...")
    t0 = time.time()
    P = sample_params(N_TRAIN + N_TEST)
    S = np.array([surface(p) for p in P])
    gen_s = time.time() - t0
    per_surface = gen_s / len(P)
    ok = np.isfinite(S).all(axis=1) & (S < 2.5).all(axis=1)
    P, S = P[ok], S[ok]
    Ptr, Str = P[:N_TRAIN - 500], S[:N_TRAIN - 500]
    Pte, Ste = P[N_TRAIN - 500:], S[N_TRAIN - 500:]

    sc = StandardScaler().fit(Ptr)
    net = MLPRegressor(hidden_layer_sizes=(64, 64), max_iter=600,
                       early_stopping=True, random_state=7)
    net.fit(sc.transform(Ptr), Str)

    t0 = time.time()
    pred = net.predict(sc.transform(Pte))
    nn_per = (time.time() - t0) / len(Pte)
    mae_vp = float(np.mean(np.abs(pred - Ste))) * 100     # vol points
    worst = float(np.max(np.abs(pred - Ste))) * 100
    speedup = per_surface / max(nn_per, 1e-9)

    # sanity: leverage effect — rho<0 must produce downward skew
    demo = np.array([2.0, 0.04, 0.5, -0.7, 0.04])
    sd = surface(demo).reshape(len(TENORS), len(LOGM))
    skew_ok = bool(sd[3, 0] > sd[3, -1])

    lines = [f"# Heston lab — neural surface approximator — {date.today().isoformat()}",
             f"\nGrid: {len(TENORS)} tenors x {len(LOGM)} strikes. Train "
             f"{len(Ptr)}, test {len(Pte)} surfaces.\n",
             f"- direct pricing: {per_surface * 1e3:.1f} ms/surface "
             f"(char-function integration, {GL_N}-node GL)",
             f"- neural surface: {nn_per * 1e6:.0f} us/surface -> "
             f"speedup {speedup:,.0f}x",
             f"- test MAE: {mae_vp:.2f} vol points (worst {worst:.1f})",
             f"- sanity (rho=-0.7 gives downward skew): "
             f"{'PASS' if skew_ok else 'FAIL'}",
             f"- Verdict: {'PASS' if (mae_vp < 0.5 and speedup >= 100 and skew_ok) else 'FAIL'} "
             f"(gates: MAE<0.5 vp, speedup>=100x, skew sanity)",
             "\nDemo surface (kappa=2, theta=.04, sig_v=.5, rho=-.7, v0=.04), "
             "IV% rows=tenors, cols=log-moneyness -0.3..0.3:"]
    for i, T in enumerate(TENORS):
        lines.append(f"  T={T:>5.2f}y: " + " ".join(f"{v * 100:5.1f}"
                                                    for v in sd[i]))
    (ROOT / "output").mkdir(exist_ok=True)
    out = ROOT / "output" / f"heston_lab_{date.today().isoformat()}.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))

    import joblib
    joblib.dump({"net": net, "scaler": sc, "tenors": TENORS, "logm": LOGM},
                ROOT / "output/heston_net.joblib")

    print(f"\nmodel cached: state/cache/heston_net.joblib | report: {out}")


if __name__ == "__main__":
    main()
